Repository medic/cht-docs, pull requests merged in 2024-10, with the labels that each got.

#1581 fix(#827): Change source of text from form to task
  content/en/building/features/tasks/_index.md
  content/en/design/best-practices/_index.md
  content/en/design/best-practices/img/anatomy-task.png
Labels: hacktoberfest-accepted

#1588 fix(#1553): Replace old CHT logo on docsite
  content/en/building/guides/integrations/openmrs.md
  content/en/building/guides/integrations/openmrs/cht-openmrs.jpeg
  content/en/building/guides/integrations/openmrs/cht-openmrs.jpg
  content/en/building/guides/integrations/rapidpro/sequence-diagram.png
Labels: hacktoberfest-accepted

#1592 fix(#1586): Removed ToC as it is a duplication of the side bar
  content/en/building/guides/privacy/policy.md
Labels: hacktoberfest, hacktoberfest-accepted

#1593 fix(#1475): Fix overlapped copy link icon on local install
  assets/scss/_variables_project.scss
Labels: hacktoberfest, hacktoberfest-accepted

#1622 Move training section
  content/en/building/examples/training.md
  content/en/building/features/training/_index.md
  content/en/building/guides/data/training-instance.md
  content/en/building/guides/security/securely-onboarding-users-at-scale.md
  content/en/building/training/_index.md
  content/en/building/training/onboarding/_index.md
  content/en/building/training/onboarding/training-app.png
  content/en/building/training/training-cards-resources/_index.md
  content/en/building/training/training-cards-resources/available-trainings/floating-action-button/ui_change_floating_action_button-media/images/actions-list.png
  content/en/building/training/training-cards-resources/available-trainings/floating-action-button/ui_change_floating_action_button-media/images/fab.png
  content/en/building/training/training-cards-resources/available-trainings/floating-action-button/ui_change_floating_action_button-media/images/old-actions.png
  content/en/building/training/training-cards-resources/available-trainings/floating-action-button/ui_change_floating_action_button.properties.json
  content/en/building/training/training-cards-resources/available-trainings/floating-action-button/ui_change_floating_action_button.xlsx
  content/en/building/training/training-cards-resources/available-trainings/floating-action-button/ui_change_floating_action_button.xml
  content/en/building/training/training-cards-resources/available-trainings/more-options/ui_change_more_options-media/images/new_actions.png
  content/en/building/training/training-cards-resources/available-trainings/more-options/ui_change_more_options-media/images/old_actions.png
  content/en/building/training/training-cards-resources/available-trainings/more-options/ui_change_more_options.properties.json
  content/en/building/training/training-cards-resources/available-trainings/more-options/ui_change_more_options.xlsx
  content/en/building/training/training-cards-resources/available-trainings/more-options/ui_change_more_options.xml
  content/en/building/training/training-cards-resources/images/floating-action-button.png
  content/en/building/training/training-cards-resources/images/more-options.png
  content/en/building/training/training-cards/_index.md
  content/en/building/training/training-cards/step-1-xls-form.png
  content/en/building/training/training-cards/step-2-xls-form-id.png
  content/en/building/training/training-cards/step-5-file-structure.png
  content/en/core/releases/4.2.0.md
Labels: project: Content Reorganization

#1642 Move features training into index file
  content/en/building/features/training/_index.md
  content/en/building/training/onboarding/_index.md
  content/en/building/training/training-cards-resources/_index.md
  content/en/building/training/training-cards/_index.md
  content/en/building/training/training-cards/training-cards-configuration.md
  content/en/building/training/training-cards/training-cards-configuration/step-1-xls-form.png
  content/en/building/training/training-cards/training-cards-configuration/step-2-xls-form-id.png
  content/en/building/training/training-cards/training-cards-configuration/step-5-file-structure.png
  content/en/building/training/training-cards/training-deck.png
  content/en/core/releases/4.2.0.md
  content/en/running-programs/training.md
Labels: project: Content Reorganization
